chain: "iotex"
clientURL: "api.iotex.one:443"
privateKey: ""
slackWebHook: ""
interval: 1m
batchSize: 100
database:
  uri: "root:kdfjjrU64fjK58H@tcp(database:3306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "iotex-to-ethereum"
    relayerURL: ":7000"
    cashierContractAddress: "io1gsr52ahqzklaf7flqar8r0269f2utkw9349qg8"
    validatorContractAddress: "0xd8165188ccc135b3a3b2a5d2bc3af9d94753d955"
    startBlockHeight: 9526978
    transferTableName: "iotex_transfers"
    tokenPairs:
      # WETH
      - token1: "io1qfvgvmk6lpxkpqwlzanqx4atyzs86ryqjnfuad"
        token2: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
      # WBTC
      - token1: "io1c7unwg8h8vph89xwqru4f7zfa4yy5002wxvlrm"
        token2: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
      # BUSD
      - token1: "io14nhfkywdfvl40evgsqnh43ev33q6he8yez8c8a"
        token2: "0x4Fabb145d64652a948d72533023f6E7A623C7C53"
      # UNI
      - token1: "io1ahh04jn2zkqlug6feh7rpq75a75p3rj42hp4ch"
        token2: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984"
      # PAXG
      - token1: "io19fsq8e9krrlng4ay5gyq6q5tqfym28yq9ly0fz"
        token2: "0x45804880De22913dAFE09f4980848ECE6EcbAf78"
      # CYC
      - token1: "io1f4acssp65t6s90egjkzpvrdsrjjyysnvxgqjrh"
        token2: "0x8861cfF2366C1128fd699B68304aD99a0764Ef9a"
      # W-IOTX
      - token1: "io15qr5fzpxsnp7garl4m7k355rafzqn8grrm0grz"
        token2: "0x6fB3e0A217407EFFf7Ca062D46c26E5d60a14d69"
      # MIST
      - token1: "io1kf2u4nnp2m2h4p6zvj42z89qdmw9hkz3m4r9uq"
        token2: "0x88ACDd2a6425c3FaAE4Bc9650Fd7E27e0Bebb7aB"
        
  - id: "iotex-to-heco"
    relayerURL: ":7002"
    cashierContractAddress: "io1s6m6j3cdj0j7hlgupx0pww7wscvkepdjfwgkra"
    validatorContractAddress: "0xDe9395d2f4940aA501f9a27B98592589D14Bb0f7"
    startBlockHeight: 2431000
    transferTableName: "iotex_to_heco_transfers"
    tokenPairs:
  - id: "iotex-to-bsc"
    relayerURL: ":7003"
    cashierContractAddress: "io1zjlng7je02kxyvjq4eavswp6uxvfvcnh2a0a3d"
    validatorContractAddress: "0x116404F86e97846110EA08cd52fC2882d4AD3123"
    startBlockHeight: 5177821
    transferTableName: "iotex_to_bsc_transfers"
    tokenPairs:
  - id: "iotex-to-matic"
    relayerURL: ":7004"
    cashierContractAddress: "io12s9f9hv4zsr7umy5hxt6g0k0xr4x6pxdp5w998"
    validatorContractAddress: "0xFBe9A4138AFDF1fA639a8c2818a0C4513fc4CE4B"
    startBlockHeight: 10000000
    transferTableName: "iotex_to_matic_transfers"
    tokenPairs:
