chain: "ethereum"
clientURL: ""
privateKey: ""
slackWebHook: ""
interval: 1m
batchSize: 40
database:
  uri: "root:kdfjjrU64fjK58H@tcp(database:3306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "ethereum-to-iotex"
    relayerURL: ":7001"
    startBlockHeight: 11827636
    validatorContractAddress: "io10xr64as4krm5nufd5l2ddc43al6tl0smumkg7y"
    cashierContractAddress: "0xa0fd7430852361931b23a31f84374ba3314e1682"
    transferTableName: "ethereum_transfers"
    tokenPairs:
      # WETH
      - token2: "io1qfvgvmk6lpxkpqwlzanqx4atyzs86ryqjnfuad"
        token1: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
      # WBTC
      - token2: "io1c7unwg8h8vph89xwqru4f7zfa4yy5002wxvlrm"
        token1: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
      # BUSD
      - token2: "io14nhfkywdfvl40evgsqnh43ev33q6he8yez8c8a"
        token1: "0x4Fabb145d64652a948d72533023f6E7A623C7C53"
      # UNI
      - token2: "io1ahh04jn2zkqlug6feh7rpq75a75p3rj42hp4ch"
        token1: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984"
      # PAXG
      - token2: "io19fsq8e9krrlng4ay5gyq6q5tqfym28yq9ly0fz"
        token1: "0x45804880De22913dAFE09f4980848ECE6EcbAf78"
      # CYC
      - token2: "io1f4acssp65t6s90egjkzpvrdsrjjyysnvxgqjrh"
        token1: "0x8861cfF2366C1128fd699B68304aD99a0764Ef9a"
      # W-IOTX
      - token2: "io15qr5fzpxsnp7garl4m7k355rafzqn8grrm0grz"
        token1: "0x6fB3e0A217407EFFf7Ca062D46c26E5d60a14d69"
      # MIST
      - token2: "io1kf2u4nnp2m2h4p6zvj42z89qdmw9hkz3m4r9uq"
        token1: "0x88ACDd2a6425c3FaAE4Bc9650Fd7E27e0Bebb7aB"
